services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TicketSwap\Kafka\Outbox\:
        resource: '../../../*'
        exclude: '../../{DependencyInjection}'
