services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TicketSwap\Kafka\Outbox\:
        resource: '../../../*'
        exclude: '../../{DependencyInjection}'

    TicketSwap\Kafka\Outbox\Clock\SystemClock:
        alias: TicketSwap\Kafka\Outbox\Clock\RealSystemClock

    TicketSwap\Kafka\Outbox\Repository\OutboxMessageRepository:
        alias: TicketSwap\Kafka\Outbox\Repository\DoctrineOutboxMessageRepository

    TicketSwap\Kafka\Outbox\Producer\Producer:
        alias: TicketSwap\Kafka\Outbox\Producer\OutboxProducer
