name: Tests

on: [ push ]

jobs:
    run:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: [ '8.0', '8.1' ]
                dependencies: [ 'highest', 'lowest' ]

        name: PHP ${{ matrix.php-versions }} tests with ${{ matrix.dependencies }} dependencies
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                env:
                    fail-fast: true
            -   name: Install dependencies
                uses: ramsey/composer-install@2.1.0
                with:
                    dependency-versions: ${{ matrix.dependencies }}
            -   name: Run tests
                run: composer run tests
            -   name: Run static analysis
                run: composer run phpstan
