name: Tests

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.0', '8.1']
        dependencies: ['normal', 'highest', 'lowest']

    name: PHP ${{ matrix.php-versions }} tests with ${{ matrix.dependencies }} dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: composer-cache
        with:
          path: vendor
          key: ${{ matrix.php-versions }}-${{ matrix.dependencies }}-composer

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: pecl
        env:
          fail-fast: true

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          if [ "${{ matrix.dependencies }}" = "normal" ]; then composer install --prefer-dist --no-progress --no-suggest; fi;
          if [ "${{ matrix.dependencies }}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-progress --no-suggest; fi;
          if [ "${{ matrix.dependencies }}" = "highest" ]; then composer update --prefer-dist --no-progress --no-suggest; fi;

      - name: Run test suite
        run: composer run test

      - name: Run static analysis
        run: composer run sa
